---
apiVersion: v1
kind: Namespace
metadata:
  name: interswitch

---
apiVersion: v1
kind: Service
metadata:
  name: interswitch-service
  namespace: interswitch
  labels:
    app: interswitch-deployment
spec:
  type: LoadBalancer   
  selector:
    app: interswitch-deployment
  ports:
    - port: 8000
      targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: interswitch-deployment
  namespace: interswitch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interswitch-deployment
  template:
    metadata:
      labels:
        app: interswitch-deployment
    spec:
      containers:
        - name: interswitch-deployment
          image: 637423239767.dkr.ecr.eu-west-1.amazonaws.com/interswitch-ecr:latest
          ports:
            - containerPort: 8000
              name: http


